### ISSUE TITLE
No image is saved, no error is given

### ISSUE THREAD

**Issue by samtuke** [integratedexperts/behat-screenshot#21]
Having followed the setup instructions and added a screenshot step as desecribed to my feature test, no screenshot is saved, regardless of the directory that is specified by `dir:` in behat.yml, and no error is printed either to terminal or PHP error log. 

The step `Then I save screenshot` passes and is printed green in terminal output. I have tried using /tmp and my home directory as values of `dir:` but no files there are created (either on screenshot step succeed, or on step fail).

Shouldn't there be error output if there was a problem?

My behat.yml:
``` yml
default:
    autoload:
        - %paths.base%/tests/features/bootstrap
    suites:
        default:
            paths:
                - %paths.base%/tests/features
            contexts:
                - IntegratedExperts\BehatScreenshotExtension\Context\ScreenshotContext
                - FeatureContext:
                    base_url: http://local.pl3
                    db_user: foo
                    db_password: foo
                    db_name: foo
                    admin_username: foo
                    admin_password: foo

    extensions:
        Behat\MinkExtension:
            # Change to you custom url:
            base_url:  'http://local.pl3'
            show_auto: true
            show_cmd: epiphany %s
            sessions:
                default:
                    #goutte: ~
                    selenium2: ~
                    
        IntegratedExperts\BehatScreenshotExtension:
            dir: /tmp
            fail: true
            purge: false
```
