### ISSUE TITLE
Configurable screen size for responsive screenshots

### ISSUE THREAD

**Issue by leymannx** [integratedexperts/behat-screenshot#30]
Currently the screen size gets set to 1440 x 990 pixels for all screenshots.

https://github.com/integratedexperts/behat-screenshot/blob/37f2c9c43122c188ce604d1555968b6deaa422dc/src/IntegratedExperts/BehatScreenshotExtension/Context/ScreenshotContext.php#L79-L86

It would be wonderful to use this extension to make responsive screenshots as well.

Easiest probably would be to make this part of the config in the `behat.yml`. Maybe something like adding a new `size` key to fetch the desired `width` and `height`:

```yaml
default:
  suites:
    default:
      contexts:
        - IntegratedExperts\BehatScreenshotExtension\Context\ScreenshotContext
        - FeatureContext
  extensions:
    IntegratedExperts\BehatScreenshotExtension:
      dir: %paths.base%/screenshots
      fail: true
      purge: false
      size:
        width: 320
        height: 568 
```

But an even nicer feature would be to have the ability to pass this as an option directly from the step. Like for example:

```
  Given I am on "http://google.com"  
  Then I save [320, 568] screenshot
```

or 

```
  Given I am on "http://google.com"  
  Then I save [320, 568] responsive screenshot
```

**Comment by alexdesignworks** [comment]
@leymannx check out https://github.com/integratedexperts/behat-relativity for wide support of responsive screens

**Comment by xurizaemon** [comment]
🖐🏼 OK, here's a PR.

> Easiest probably would be to make this part of the config in the behat.yml. Maybe something like adding a new size key to fetch the desired width and height.

IMO we don't need to introduce an additional configuration, since Selenium2 already has this via browser switches, like this (Chrome example based on this repo's behat.yml with window size added, json => yaml for legibility).

```
      selenium2:
        wd_host: "http://selenium:4444/wd/hub"
        capabilities: 
          browser: "chrome"
          version: "*"
          marionette: true
          extra_capabilities:
            chromeOptions:
              args:
                - "--window-size=640,480"
```

We should therefore by default respect the initial state of the browser window, rather than setting to 1440x900 in startup, and remove that resize line. (680f6b36607336c928673d5820c06a05c1fe5d4d)

We can then add the second feature proposed, which resizes the browser window for screenshots in a new stepdefinition. (c9fc430)

Then we can use it like this (2ffd7de):

```
  Then I save 1440 x 900 screenshot
  And I save 800 x 600 screenshot
```
