### ISSUE TITLE
Convert to extension so the settings could be set through config

### ISSUE THREAD

**Issue by alexdesignworks** [integratedexperts/behat-screenshot#8]
Current way of setting settings
```
default:
  suites:
    default:
      contexts:
        - IntegratedExperts\BehatScreenshot\ScreenshotContext:
          -
            dir: %paths.base%/screenshots
            fail: true
            purge: false
        - FeatureContext     
```

Proper way of setting settings
```
default:
  suites:
    default:
      contexts:
        - FeatureContext     
        - IntegratedExperts\BehatScreenshot\ScreenshotContext
      extensions:
          IntegratedExperts\BehatScreenshot\ScreenshotContext:
            dir: %paths.base%/screenshots
            fail: true
            purge: false
```
